
# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

media_player:
    - platform: onkyo
      name: Onkyo
      max_volume: 70
      receiver_max_volume: 80
      disable_select_hdmi_output: True
      sources:
        cd: Vinyl
        internet-radio-1: AirPlay

binary_sensor:
  - platform: template
    sensors:
      plattenspieler:
        device_class: power
        friendly_name: "Plattenspieler"
        value_template: "{{ not is_state('sensor.vcc_voltage', 'unavailable') }}"

logger:
  default: warning
  logs:
    homeassistant.components.onkyo: debug
